### ISSUE TITLE
Any chance to get this deployd to Maven Central?

### ISSUE THREAD

**Issue by Nilzor** [alexbirkett/controllers-for-android#6]
Could not find it on Maven Central. Would be easier for people to adopt if it's just a one-liner in build.gradle or (5-liner in) maven.pom

http://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by alexbirkett** [comment]
So I managed to upload to bintray. I've sent them a request to add to jCenter https://bintray.com/alexbirkett/maven/controllers-for-android

**Comment by alexbirkett** [comment]
BTW @lassem I had to rename the java package to match my domain :( Sorry

**Comment by alexbirkett** [comment]
Fixed https://bintray.com/bintray/jcenter?filterByPkgName=controllers-for-android
